modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/Kenny-Hui/NeoMSD/issues"

[[mods]]
modId = "msd"
version = "${version}"
displayName = "NeoMSD"
authors = "AIDA64S, Santorsia, Zbx1425, LX86"
description = "A Station Decoration Addon for the Minecraft Transit Railway Mod"
logoFile = "icon.png"

[[dependencies.msd]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.msd]]
modId = "architectury"
type = "required"
versionRange = "[1.26.37,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.msd]]
modId = "mtr"
reason = "This addon requires NeoMTR. (Not MTR 3 nor MTR 4!)"
type = "required"
versionRange = "[300.6.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "msd-common.mixins.json"